// user login types
export const userConstants = {

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  GET_USERS: 'GET_USERS',
  ADD_FRIEND: 'ADD_FRIEND'
}

export const conversationConstants = {
  CREATE: 'CREATE',
  SET_CURRENT: 'SET_CURRENT',
  ALL: 'ALL',
  GET_CONVERSATIONS: 'GET_CONVERSATIONS'
}

export const messageConstants = {
  // CREATE: 'CREATE',
  RECEIVED: 'RECEIVED'
}